Fix compilation problems when running nnapi_delegate_test as part of CTS
This fixes the following two problems:

1.
    In file included from external/tensorflow/tensorflow/lite/kernels/test_util.h:30:
    external/tensorflow/tensorflow/lite/testing/util.h:21:10: fatal error: 'tensorflow/lite/string.h' file not found
    #include "tensorflow/lite/string.h"
             ^~~~~~~~~~~~~~~~~~~~~~~~~~

2.
    ld.lld: error: undefined symbol: testing::internal::FormatMatcherDescription(bool, char const*, std::__ndk1::vector<std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> >, std::__ndk1::allocator<std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > > > const&)
    >>> referenced by nnapi_delegate_test.cc:34 (external/tensorflow//tensorflow/lite/delegates/nnapi/nnapi_delegate_test.cc:34)
    >>>               nnapi_delegate_test.o:(tflite::(anonymous namespace)::QuantizedNearMatcher::gmock_Impl<std::__ndk1::tuple<unsigned char const&, int const&> >::DescribeTo(std::__ndk1::basic_ostream<char, std::__ndk1::char_traits<char> >*) const) in archive out/target/product/crosshatch/obj_arm/STATIC_LIBRARIES/CtsTfliteNnapiDelegateTests_static_intermediates/CtsTfliteNnapiDelegateTests_static.a

Bug: 130342510
Bug: 124643616
Test: mma CtsTfliteNnapiDelegateTests_static (with change I823a3071b4e45c5bf00a84334793347339f1cfa4)
Change-Id: I2a3126794de8f30bd80e0a55b075fd21a201a738
Merged-In: I2a3126794de8f30bd80e0a55b075fd21a201a738
(cherry picked from commit 010ba1628251195c57afba368b556098c173c049)